### ISSUE TITLE
Failing to load dll on windows

### ISSUE THREAD

**Issue by XY01** [keijiro/MidiJack#1]
Getting the following error.

Windows 8.1
Unity 5.0.1f1

Failed to load 'Assets/MidiJack/Plugins/x64/MidiJackPlugin.dll' with error 'The specified module could not be found.
', GetDllDirectory returned ''. If GetDllDirectory returned non empty path, check that you're using SetDirectoryDll correctly.

I have tried in both x86 and x64 modes and still receive the same error. 
Trying to trouble shoot now but no luck yet.

**Comment by keijiro** [comment]
This change could resolve the problem. Could you try out the latest unitypackage?
https://github.com/keijiro/MidiJack/commit/f5b599aaaa54d71faf5c95e99e0b0a02762c886f

**Comment by XY01** [comment]
Sweet. Works perfectly.

Cheers mate, keep up the rad work
