### ISSUE TITLE
Beginner Stuff

### ISSUE THREAD

**Issue by amunrarara** [keijiro/MidiJack#10]
Hey folks, I'm having trouble using the most basic functions of MidiJack. I have a knob that I want to return the value of when it has changed. The MidiMaster.GetKnob function returns a float value and I want to store this in a variable, so I use the function to assign value to this variable. In this case, I am using knob number 10, and I did not specify a channel. I've tried the following calls, but they're all returning incorrect stuff:

float temp = MidiMaster.GetKnob(0xB0, 10);
float temp = MidiMaster.GetKnob(10, 0);

Obviously they're not correct. But I am at a loss here. Any help is amazingly appreciated. Thank you.

**Comment by amunrarara** [comment]
Ask and you shall discover on your own :-) Figured it out. Took a while!

**Comment by niorg2606** [comment]
Solution?
