### ISSUE TITLE
Mac OSX problems

### ISSUE THREAD

**Issue by Pearlcorder** [keijiro/MidiJack#12]
Hello! 

I'm trying to set up MidiJack on Mac, but Unity doesn't detect any notes in the Example Note scene. When i click the Midi Jack tab under windows, i see my USB Midi Cable showing up.

Do you have any pointers?

**Comment by keijiro** [comment]
Does the monitor show incoming messages when you hit the keys on the device? Or just showing its name?

![](http://keijiro.github.io/MidiJack/monitor.png)

**Comment by Pearlcorder** [comment]
Hi!

Yes actually it does. It looks like this:

**Comment by Pearlcorder** [comment]
Wait! Now it works for no reason. Thanks for replying anyway :)
