### ISSUE TITLE
5 note limit

### ISSUE THREAD

**Issue by niorg2606** [keijiro/MidiJack#14]
I created a Unity project with MidiJack, and it only seems to have a polyphony of 5. Could this possibly be raised?
If nobody else has this problem, it's just my code and I need to git gud :P

**Comment by keijiro** [comment]
I've never experienced such a problem. Could you verify it with the "Example Note" test scene and another device?

https://github.com/keijiro/MidiJack/tree/master/Assets/Example%20Note

**Comment by niorg2606** [comment]
Whoops! Just realized that the text had a limit
Gosh, I suck at this :/
