### ISSUE TITLE
unity standalone build

### ISSUE THREAD

**Issue by dHeaper** [keijiro/MidiJack#15]
Hi. I am loving this tool and use it to move scene elements in Unity. One issue I'm having s that I am unable to build a standalone .exe and get my controller to work. The build is created, just no midi support.. any help would be much appreciated!

**Comment by keijiro** [comment]
Did you close Unity Editor before running the build? Unity Editor should be closed before running the standalone build because MIDI devices are exclusively retained by a single application on some systems.

**Comment by dHeaper** [comment]
That seemed to do it... sorry for the trouble, love the tool!
