### ISSUE TITLE
just a little help please

### ISSUE THREAD

**Issue by Dimavj** [keijiro/MidiJack#20]
Hi guys, I'm using MidiJack with a touchOsc controller, 
I'm sending cc to my scene to change a color in a material. it's all ok, but, 
as I use a Random.Range to get some variety of colors, and I listen to cc in update function...
then the color randomizes constantly, 
My solution consists in restrict the color calculation only when update receives some cc data from MidiJack.
But i don't know what to write in the If statement to check only if there is some data entering, not the data..
I tried: that... but no results...  if( MidiDriver.Instance.GetKnob(0, knobNumber, 0) != 0) {  colorize(): }
Well, there' s someone who has a solution for that?
thanks a lot..
A.C.

**Comment by keijiro** [comment]
I'd recommend using a note instead of a CC.

**Comment by Dimavj** [comment]
... a note? .. I need continuous controls, as faders to change parameters real time, I think a note has not this functionality...
well, I just need to check (boolean) if there's entering data on my cc... any suggestion?
Thank you Keijiro!
A.

**Comment by keijiro** [comment]
You can use the delegate to capture incoming MIDI CC messages.

https://github.com/keijiro/MidiJack/blob/master/Assets/MidiJack/MidiDriver.cs#L112

But implementing a delegate is a little bit troublesome. Just storing the knob value and comparing it every frame is safe and easier than the delegate approach.
