### ISSUE TITLE
Works in Editor, not in Build

### ISSUE THREAD

**Issue by emilysa** [keijiro/MidiJack#23]
Hi,
The controller works perfectly in the editor, but when I build the game, the controller no longer works with the executable.  It still triggers (I can see the triggers in the output.log), but nothing happens in the game.  Any suggestions?

**Comment by keijiro** [comment]
Did you close Unity Editor before running the build? Unity Editor should be closed before running the standalone build because MIDI devices are exclusively retained by a single application on some systems.

**Comment by emilysa** [comment]
Yes, the editor is closed.  Since posting, one of the .exes is working (the channels were incorrect in my initialization json file).  I'm still working on debugging the other exe, but I will now compare both games to make sure I'm not missing anything critical.  I will update if/when it's resolved, but if you have any suggestions of where to look, I'd be super appreciative.  Thank you for your quick response time!

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.
