### ISSUE TITLE
MidiJack for Unity 2017

### ISSUE THREAD

**Issue by cpatin10** [keijiro/MidiJack#29]
Hi Mr. Keijiro
I am a university student that wants to create a game with Unity for Mac OS where a piano keyboard acts as the control. I am new to Unity so I do not know whether this is a stupid question, but before I begin with development I want to know whether MidiJack can be used with Unity 2017.

Thank you very much for your hard work.

**Comment by keijiro** [comment]
It should work (please report an issue if it doesn't work).
