### ISSUE TITLE
Knob range larger than 0 to 127

### ISSUE THREAD

**Issue by Terahertz0** [keijiro/MidiJack#30]
Hi keijiro, I am using Fl studio as midi out device, Fl can be configured to output a midi value more than 127, like from 0 to 1000. When I tested this with this plugin it didn't work properly, I am also using "loopMIDI" to link it to unity, Is there any modification i can do to have a larger range in the plugin, or the problem is coming from the midi link between Fl and unity "loopMIDI"?, i need this cuz i am controlling transform of objects and 128 points makes the motion not so smooth.
Thanks in advance, and also for creating this really useful plugin 😄

**Comment by keijiro** [comment]
In the MIDI specification, the value range of CC is limited between 0-127. So if you're using CC, values over 127 never work.

It seems FL supports RPN/NRPN for the controllers. They may be able to send multiple-byte values, but MidiJack doesn't support them.

**Comment by keijiro** [comment]
I'm closing this ticket. Feel free to reopen for further questions.

**Comment by Terahertz0** [comment]
So what is your suggestion to solve this problem? I need to control transforms and effects from FL studio and midi seems the only proper way available. Is it easy to implement RPN/NRPN for midi ? so i can do it myself with one year of experience in unity, or should I try to find another way to smooth the motion from unity's side, or leave midi altogether and try to control stuff with frequency and amplitude of audio signals from FL xD, ur suggestions are greatly appreciated 😃

**Comment by keijiro** [comment]
I don't have any experience on handling RPN/NRPN data. So, I have no idea about it.

In my personal opinion, using CC and smoothing it in Unity's side is enough for most cases.
