### ISSUE TITLE
Integration with new InputSystem

### ISSUE THREAD

**Issue by rsodre** [keijiro/MidiJack#41]
Not sure if it's possible to add a custom device to the new Input System, but would be nice to configure MIDI from there.

**Comment by keijiro** [comment]
Nice catch, but unfortunately, my conclusion is that it's not possible at the moment. The new system is well-designed for input devices with 10 or 20 control elements, but not for a device with 256 control elements (128 notes + 128 CCs).

I'll revisit the possibility when the new system is finalized.

**Comment by rsodre** [comment]
Btw, I created a request at Unity's own repository too. No comments yet...
https://github.com/Unity-Technologies/InputSystem/issues/537

**Comment by JimmyCushnie** [comment]
@keijiro why do you feel the new input system is not well-designed for large devices? I looked through the ["how to create custom devices"](https://docs.unity3d.com/Packages/com.unity.inputsystem@0.9/manual/HowDoI.html#-create-my-own-custom-devices) section of the documentation and it looks fine to me for large devices.

Furthermore, the new system handles (non-musical) keyboards just fine, and those have 110 inputs.

**Comment by keijiro** [comment]
@JimmyCushnie Right.

**Comment by JimmyCushnie** [comment]
...what? I think you may have responded to the wrong thread

**Comment by keijiro** [comment]
@JimmyCushnie I meant your understanding is right.

**Comment by JimmyCushnie** [comment]
Ah, so this has changed since you made your comment in April?

Do you think making a MidiJack port for the new input system is something you might now do, then?

**Comment by keijiro** [comment]
@JimmyCushnie No. I was just wrong.

I'll start a new project instead of extending MidiJack, I don't have time for a while though.

**Comment by JimmyCushnie** [comment]
That's excellent news, I look forwards to using your new project :)

**Comment by keijiro** [comment]
I finished the new project. Now you can get MIDI input via the new Input System.

https://github.com/keijiro/Minis

**Comment by JimmyCushnie** [comment]
Thank you for the notification. Your new system looks awesome, and I'll be using it in my project!
