### ISSUE TITLE
Update plugin code to use lib RtMidi

### ISSUE THREAD

**Issue by Blist** [keijiro/MidiJack#47]
Hello,

It's would be cool to use RtMidi library to harmonize code between Windows and MacOS, and to get it works with linux too.

http://www.music.mcgill.ca/~gary/rtmidi/index.html

Thanks for your works !
Best Regards

**Comment by keijiro** [comment]
When I checked it last time, it seemed to lack some important features so declined the idea.

I'll revisit it and reconsider the idea.

**Comment by Blist** [comment]
Hi,
I've do some test on RtMidi on Linux, Mac on Windows. It's seems to work well (I didn't test input lag or something like that). the only thing that isn't collected is the id of each midi controller connected.

https://github.com/Blist/MidiJack/commit/0c59e33a8f7f1c59fe621fcae85124d7a11fac97

**Comment by keijiro** [comment]
I developed a new MIDI plugin for Unity's new Input System. RtMidi is used in this plugin.

https://github.com/keijiro/Minis

I'm closing this issue now as the suggestion is adopted in the new project.
