### ISSUE TITLE
Keyboard Midi Controller

### ISSUE THREAD

**Issue by Bramichou** [keijiro/MidiJack#49]
Hey i want to use my keboard as Midi Controller with MidiJack, but it doesnt recognize the keboard as Midi Controller in the Window -> Midi Jack, what am i suppose to do @keijiro  ? Thank you !

**Comment by keijiro** [comment]
Is there any other application using the MIDI device? I'd recommend closing all the other applications, relaunching Unity and retrying it.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen if it still reproduces.
