### ISSUE TITLE
Midi out

### ISSUE THREAD

**Issue by michelteggeler** [keijiro/MidiJack#5]
Hi Keijiro Takahashi,

A truly wonderful piece of code, I followed the instructions and it just works, brilliant !!

But after installing it I found out it only has midi in functionalities, so I have to tryout your older piece of code 'Unity MIDI Bridge', which I hope will work just as simple as MidiJack.

Besides the lack of midi out, it works great, hope to see midi out someday in this version, :)

Warmest regards,

Michel Teggeler

**Comment by keijiro** [comment]
Thanks for the feedback! Although I agree with you, I'd like to close this issue because it's duplicated.

https://github.com/keijiro/MidiJack/issues/3
