### ISSUE TITLE
Inifinite midi device detected which freezes the editor

### ISSUE THREAD

**Issue by MlleDR** [keijiro/MidiJack#50]
Hello @keijiro,

It's the first time I'm using your plugin to use my Korg MicroKontrol device. When checking the device in the MidiJack window, I get the following messages and they seem to be infinite. Finally, it freezes the editor which I have to kill in the task manager. Any idea about this? Thanks!

![image](https://user-images.githubusercontent.com/27687330/63879519-2a32e280-c9cc-11e9-8d73-96d7501f05ec.png)

_Using Unity 2019.2.0f1_

**Comment by keijiro** [comment]
Are you using the KORG MIDI driver? If so, could you try uninstalling it? Actually KORG MIDI devices don't need it.

**Comment by MlleDR** [comment]
Hello @keijiro, I uninstalled the driver and the editor that comes with the device. But the bug was still there. But with the [troubleshooting ](https://github.com/keijiro/MidiJack/wiki/Troubleshooting)tip you've posted, bingo ! Many many thanks !
