### ISSUE TITLE
Does it work with Hololens 1 ?

### ISSUE THREAD

**Issue by ankushmp** [keijiro/MidiJack#51]
Hi 

I am working on an application in which i want to get input from the yamaha keyboard and play it in Hololens. Do you think this plugin will work according to my requirements? 

If not can you suggest me what to do to achieve it?

Thanks in advance

**Comment by keijiro** [comment]
I don't have experience with HoloLens, so I'm not sure if it works on the device. It would work if it supports native x86-64 binary.

Just out of curiosity, is it possible to connect a USB keyboard to Hololens? As far as I know, it doesn't have USB host functionality.

**Comment by ankushmp** [comment]
Thanks for the quick response.

Hololens 1 does support native x86 library but haven't check if it can connect to USB keyboard but USB keyboard working fine in editor. 

Just another question, Right now i am getting MIDI input in the form of messages, is there any way i can convert those messages to MIDI file so that i can play that inside unity?
OR 

if i can generate some sound using those MIDI messages ?

Any help would be appreciated.

**Comment by keijiro** [comment]
> Just another question, Right now i am getting MIDI input in the form of messages, is there any way i can convert those messages to MIDI file so that i can play that inside unity?
> OR
> if i can generate some sound using those MIDI messages ?

MidiJack doesn't provide any functionality about MIDI recording or audio playback.

**Comment by ankushmp** [comment]
Does Unity-Midi-Input plugin provide any of this functionality ?

**Comment by keijiro** [comment]
I'm not sure what "Unity-Midi-Input plugin" is. I'd recommend searching Unity Asset Store for other MIDI solutions.

Sorry but this issue tracker is solely used for the purpose of improving the quality of MidiJack. I'm closing this issue as the original question has been answered. I'd recommend using Unity Forum or some other developer community for further discussion.
