### ISSUE TITLE
Hololens2(ARM) usage

### ISSUE THREAD

**Issue by hiroyuki26** [keijiro/MidiJack#58]
Hello,

I want to develop hololens2 application which has a function receiving/sending MIDI.
Does "MIDIjack"  support for Hololens2(ARM)?

Please let me know, if you have good way(ex: sample project, library ).

**Comment by keijiro** [comment]
> Does "MIDIjack" support for Hololens2(ARM)?

No. It only supports x86-64 on Windows.

> Please let me know, if you have good way(ex: sample project, library ).

I don't know any alternative. I wonder if you can find something on Asset Store.
