### ISSUE TITLE
Midijack undetected with AKAI MPK Midi Controller? 

### ISSUE THREAD

**Issue by ttestffeed** [keijiro/MidiJack#60]
Hello, im using an AKAI MPK Midi Controller as my device, but as I open the Midi Jack Window, the device is not detected. Any solutions?

**Comment by keijiro** [comment]
It should be detected.

Please note that this project is not actively developed any more. I'd recommend using the new MIDI input plugin called Minis: https://github.com/keijiro/Minis

**Comment by ttestffeed** [comment]
Hello Mr. Keijiro thank you so much for your reply,
I downloaded Minis and have a few questions. How do I open the library or
the Midi window in unity?
Thank you

**Comment by keijiro** [comment]
Please check the How To Install section on README.

I'd appreciate if you could use the proper issue tracker for questions about Minis. Please don't continue this thread. https://github.com/keijiro/Minis/issues
