### ISSUE TITLE
Upgrade to Unity 2020

### ISSUE THREAD

**Issue by ARtronClassicStudio** [keijiro/MidiJack#62]
Hello I have Unity 2020 and Unity 5:
There are no bugs in 2020 but the midi keyboard is not working, 
since i don't have a midi keyboard i use android as input to my keyboard.
I try in unity 5 everything works there.
can i somehow upgrade to version 2020?

P.S: yes I know you have a new plugin "Minis" but I don't want to use the new inpput system.

**Comment by keijiro** [comment]
I don't have time for maintaining this project, so please don't expect a fix.

I leave this issue ticket opened for recording purpose.

**Comment by ARtronClassicStudio** [comment]
Then do you mind if I update the plugin and put it on my repositories?

**Comment by keijiro** [comment]
This is an open source project under the MIT license. You can do (almost) whatever you want to do.

**Comment by ARtronClassicStudio** [comment]
hello, I made an update to this plugin, if you are interested you can see it [here](https://github.com/ARtronClassicStudio/MidiJackEngine) :)

**Comment by keijiro** [comment]
I'm closing this issue now as assuming that you solved the problem on your side. Please feel free to reopen it for further problems.
