### ISSUE TITLE
Detected MIDI devices: device unknown

### ISSUE THREAD

**Issue by jrdndj** [keijiro/MidiJack#63]
Hi! This is my first time opening an issue here. 

Im trying to work with a Kurzweil K2000 v3 (I know it is kinda old but the available drivers are until 2015). I currently connect it with a Yamaha USB UX16 adapter and everything seems to be working fine. 

However, as I add MIDIJack to my existing piano game, I open MIDI Jack Window and it only shows

```
Detected MIDI devices:
AF53EB20: unknown
```

What I want to know is if there is a certain set of MIDI tools and adaptors that are supported by this MIDIJack. This way I know if I just need a new MIDI clavinova/keyboard or if there is a way for me to update the supported devices of MIDIJack. 

I hope my issue made sense and to the mods feel free to redirect me to the proper venue if you believe that my issue is not appropriate. Thank you and have a nice day.

**Comment by keijiro** [comment]
"unknown" means "unknown but supported device". You can use it anyway.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by jrdndj** [comment]
Thank you for the feedback. I will check again and try to do some mapping and if it recognizes keypresses. I will reopen if I see further problems. Thank you very much!
