### ISSUE TITLE
Almost Stopped in U2020.3

### ISSUE THREAD

**Issue by Electricavisuals** [keijiro/MidiJack#65]
Hi 
Mr Keijiro, 
We know you are full of work and so many projects.. 
But we need an update and enhancements of your midijack, so I've tried to use it in Unity 2020.3 and (even in editor) it comes soooo muuuuch slow, almost stopped ...
So, please, we need a solution, why not to ask Unity official developers to implement Midi definitively as a default package...¿?

So, thanks anyway...
A.C.

**Comment by keijiro** [comment]
I'd recommend migrating to the new MIDI plugin called Minis. Please check README for further details.

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.

**Comment by Electricavisuals** [comment]
Thanks Keijiro, 
Just to comment, that the unitypackage comes with the old plugin, so, if you can change this, ... users like me will not get on trouble.
Thanks
