### ISSUE TITLE
Knob/Slider values always return 0.07874+ not 1

### ISSUE THREAD

**Issue by justinluk** [keijiro/MidiJack#7]
I'm not quite sure why, but when I turn up the knobs to max or sliders on my midi device the value that's returned is 0.07874+. I'm using a KORG midi device, and in the editor I can set what the lowest and highest possible values are. 

The numbers are returning properly in hex in the MIDI Jack window but when debugging the knobValue to the console, it's always a really small number.

Thoughts?

**Comment by keijiro** [comment]
0.07874 = 1/128 ... so I'm pretty sure that your device is in relative (REL) mode. Could you please check it again with absolute (ABS) mode? Maybe you can change it in the system config menu or something like that.

**Comment by justinluk** [comment]
Hmmm.. strange I don't have a setting to change it. It's a nanoKontrol2 so there are no modes to set.

It's weird that the MidiJack window shows the proper values in hex but the actual value applied is a fraction of that. 

I'll keep digging, thanks for the response!

**Comment by nicshackle** [comment]
It will show that value if your MIDI device is sending a CC value of 1. Sending a CC value of 127 will show as a 1 in unity (i.e. CC values 0-127 are mapped to a float of range 0-1 in unity). Make sure your device is configured to send a range between 0-127.
